services:
  db:
    image: postgres:latest
    env_file: .env
    restart: always
    shm_size: 128mb
    volumes:
      - db_volume:/var/lib/postgresql/data
  bot:
    build: .
    env_file: .env
    volumes:
      - .:/www/autokick
    depends_on:
      - db

volumes:
  db_volume:
    
