services:
  db:
    image: postgres:latest
    env_file: .env
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack-server
    restart: always
    ports:
      - 6379:6379

  bot:
    build: .
    env_file: .env
    restart: always
    develop:
      watch:
        - path: .
          action: sync+restart
          target: /www/autokick
          ignore:
            - node_modules
    depends_on:
      - db
      - redis

volumes:
  db_volume:
    
